apiVersion: v2
name: a11oy
description: a11oy orchestration kernel Helm chart (UDS / Zarf)
type: application
version: 0.3.1
appVersion: "uds-v0.3.1"
# Copyright 2026 SZL Holdings — SPDX-License-Identifier: Apache-2.0
