# Copyright 2026 SZL Holdings — SPDX-License-Identifier: Apache-2.0
# Allow mesh siblings + tenant gateway to reach a11oy; default-deny otherwise.
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-mesh-to-a11oy
  namespace: a11oy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: a11oy
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - "cluster.local/ns/istio-tenant-gateway/sa/tenant-ingressgateway"
              - "cluster.local/ns/amaru/sa/default"
              - "cluster.local/ns/sentra/sa/default"
              - "cluster.local/ns/killinchu/sa/default"
              - "cluster.local/ns/rosie/sa/default"
