# Copyright 2026 SZL Holdings — SPDX-License-Identifier: Apache-2.0
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: killinchu-egress
  namespace: killinchu
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: killinchu
  policyTypes: ["Egress"]
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: rosie
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: szl-receipts
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8443
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
