# Copyright 2026 SZL Holdings — SPDX-License-Identifier: Apache-2.0
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: killinchu
  namespace: killinchu
spec:
  hosts:
    - "killinchu.uds.dev"
  gateways:
    - istio-tenant-gateway/tenant
  http:
    - match:
        - uri:
            prefix: /killinchu
      route:
        - destination:
            host: killinchu.killinchu.svc.cluster.local
            port:
              number: 8080
